server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSl=false&createDatabaseIfNotExist=true&allowPulicKeyRetrieval=true
    username: root
    password: rsb34691792RSB#1
  jpa:
    hibernate:
      ddl-auto: update