version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rsb34691792RSB#1
    ports:
    - "3306:3306"
    volumes:
    - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data: